package beans;
// Generated May 23, 2010 7:11:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable{


     private int idEmpleado;
     private Cargo cargo;
     private String empleadosNombre;
     private String empleadosApellido;
     private  int empleadosCi;
     private String empleadosDir;
     private String empleadosTlfCasa;
     private String empleadosTlfMovil;
     private String empleadosContrasena;
     private Date empleadosFechaIng;
     private Date empleadosFechaFin;
     private Integer empleadosSueldoBase;
     private String empleadosLogin;
     private String empleadosCorreo;

    public Empleado() {
    }

	
    public Empleado(Cargo cargo, String empleadosNombre, String empleadosApellido, int empleadosCi, String empleadosContrasena, Date empleadosFechaIng, String empleadosLogin, String empleadosCorreo) {        
        this.cargo = cargo;
        this.empleadosNombre = empleadosNombre;
        this.empleadosApellido = empleadosApellido;
        this.empleadosCi = empleadosCi;
        this.empleadosContrasena = empleadosContrasena;
        this.empleadosFechaIng = empleadosFechaIng;
        this.empleadosLogin = empleadosLogin;
        this.empleadosCorreo = empleadosCorreo;
    }
    
    public Empleado(Cargo cargo, String empleadosNombre, String empleadosApellido, int empleadosCi, String empleadosDir, String empleadosTlfCasa, String empleadosTlfMovil, String empleadosContrasena, Date empleadosFechaIng, Date empleadosFechaFin, Integer empleadosSueldoBase, String empleadosLogin, String empleadosCorreo) {
       
       this.cargo = cargo;
       this.empleadosNombre = empleadosNombre;
       this.empleadosApellido = empleadosApellido;
       this.empleadosCi = empleadosCi;
       this.empleadosDir = empleadosDir;
       this.empleadosTlfCasa = empleadosTlfCasa;
       this.empleadosTlfMovil = empleadosTlfMovil;
       this.empleadosContrasena = empleadosContrasena;
       this.empleadosFechaIng = empleadosFechaIng;
       this.empleadosFechaFin = empleadosFechaFin;
       this.empleadosSueldoBase = empleadosSueldoBase;
       this.empleadosLogin = empleadosLogin;
       this.empleadosCorreo = empleadosCorreo;
    }
   
    public int getidEmpleado() {
        return this.idEmpleado;
    }
    
    private void setidEmpleado(int id) {
        this.idEmpleado = id;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getEmpleadosNombre() {
        return this.empleadosNombre;
    }
    
    public void setEmpleadosNombre(String empleadosNombre) {
        this.empleadosNombre = empleadosNombre;
    }
    public String getEmpleadosApellido() {
        return this.empleadosApellido;
    }
    
    public void setEmpleadosApellido(String empleadosApellido) {
        this.empleadosApellido = empleadosApellido;
    }
    public int getEmpleadosCi() {
        return this.empleadosCi;
    }
    
    public void setEmpleadosCi(int empleadosCi) {
        this.empleadosCi = empleadosCi;
    }
    public String getEmpleadosDir() {
        return this.empleadosDir;
    }
    
    public void setEmpleadosDir(String empleadosDir) {
        this.empleadosDir = empleadosDir;
    }
    public String getEmpleadosTlfCasa() {
        return this.empleadosTlfCasa;
    }
    
    public void setEmpleadosTlfCasa(String empleadosTlfCasa) {
        this.empleadosTlfCasa = empleadosTlfCasa;
    }
    public String getEmpleadosTlfMovil() {
        return this.empleadosTlfMovil;
    }
    
    public void setEmpleadosTlfMovil(String empleadosTlfMovil) {
        this.empleadosTlfMovil = empleadosTlfMovil;
    }
    public String getEmpleadosContrasena() {
        return this.empleadosContrasena;
    }
    
    public void setEmpleadosContrasena(String empleadosContrasena) {
        this.empleadosContrasena = empleadosContrasena;
    }
    public Date getEmpleadosFechaIng() {
        return this.empleadosFechaIng;
    }
    
    public void setEmpleadosFechaIng(Date empleadosFechaIng) {
        this.empleadosFechaIng = empleadosFechaIng;
    }
    public Date getEmpleadosFechaFin() {
        return this.empleadosFechaFin;
    }
    
    public void setEmpleadosFechaFin(Date empleadosFechaFin) {
        this.empleadosFechaFin = empleadosFechaFin;
    }
    public Integer getEmpleadosSueldoBase() {
        return this.empleadosSueldoBase;
    }
    
    public void setEmpleadosSueldoBase(Integer empleadosSueldoBase) {
        this.empleadosSueldoBase = empleadosSueldoBase;
    }
    public String getEmpleadosLogin() {
        return this.empleadosLogin;
    }
    
    public void setEmpleadosLogin(String empleadosLogin) {
        this.empleadosLogin = empleadosLogin;
    }
    public String getEmpleadosCorreo() {
        return this.empleadosCorreo;
    }
    
    public void setEmpleadosCorreo(String empleadosCorreo) {
        this.empleadosCorreo = empleadosCorreo;
    }

    
    public boolean equal(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Empleado other = (Empleado) obj;
        if (this.idEmpleado != other.idEmpleado) {
            return false;
        }
        if ((this.empleadosNombre == null) ? (other.empleadosNombre != null) : !this.empleadosNombre.equals(other.empleadosNombre)) {
            return false;
        }
        if ((this.empleadosApellido == null) ? (other.empleadosApellido != null) : !this.empleadosApellido.equals(other.empleadosApellido)) {
            return false;
        }
        if (this.empleadosCi != other.empleadosCi) {
            return false;
        }
        if ((this.empleadosTlfMovil == null) ? (other.empleadosTlfMovil != null) : !this.empleadosTlfMovil.equals(other.empleadosTlfMovil)) {
            return false;
        }
        if ((this.empleadosContrasena == null) ? (other.empleadosContrasena != null) : !this.empleadosContrasena.equals(other.empleadosContrasena)) {
            return false;
        }
        if (this.empleadosSueldoBase != other.empleadosSueldoBase && (this.empleadosSueldoBase == null || !this.empleadosSueldoBase.equals(other.empleadosSueldoBase))) {
            return false;
        }
        if ((this.empleadosLogin == null) ? (other.empleadosLogin != null) : !this.empleadosLogin.equals(other.empleadosLogin)) {
            return false;
        }
        if ((this.empleadosCorreo == null) ? (other.empleadosCorreo != null) : !this.empleadosCorreo.equals(other.empleadosCorreo)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 79 * hash + this.idEmpleado;
        hash = 79 * hash + (this.empleadosNombre != null ? this.empleadosNombre.hashCode() : 0);
        hash = 79 * hash + (this.empleadosApellido != null ? this.empleadosApellido.hashCode() : 0);
        hash = 79 * hash + this.empleadosCi;
        hash = 79 * hash + (this.empleadosTlfMovil != null ? this.empleadosTlfMovil.hashCode() : 0);
        hash = 79 * hash + (this.empleadosContrasena != null ? this.empleadosContrasena.hashCode() : 0);
        hash = 79 * hash + (this.empleadosSueldoBase != null ? this.empleadosSueldoBase.hashCode() : 0);
        hash = 79 * hash + (this.empleadosLogin != null ? this.empleadosLogin.hashCode() : 0);
        hash = 79 * hash + (this.empleadosCorreo != null ? this.empleadosCorreo.hashCode() : 0);
        return hash;
    }

 




}


