package datos;
// Generated May 23, 2010 7:11:23 PM by Hibernate Tools 3.2.1.GA



/**
 * EmpleadosId generated by hbm2java
 */
public class EmpleadosId  implements java.io.Serializable {


     private int idEmpleados;
     private int cargoIdCargo;

    public EmpleadosId() {
    }

    public EmpleadosId(int idEmpleados, int cargoIdCargo) {
       this.idEmpleados = idEmpleados;
       this.cargoIdCargo = cargoIdCargo;
    }
   
    public int getIdEmpleados() {
        return this.idEmpleados;
    }
    
    public void setIdEmpleados(int idEmpleados) {
        this.idEmpleados = idEmpleados;
    }
    public int getCargoIdCargo() {
        return this.cargoIdCargo;
    }
    
    public void setCargoIdCargo(int cargoIdCargo) {
        this.cargoIdCargo = cargoIdCargo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadosId) ) return false;
		 EmpleadosId castOther = ( EmpleadosId ) other; 
         
		 return (this.getIdEmpleados()==castOther.getIdEmpleados())
 && (this.getCargoIdCargo()==castOther.getCargoIdCargo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmpleados();
         result = 37 * result + this.getCargoIdCargo();
         return result;
   }   


}


