package datos;
// Generated May 23, 2010 7:11:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int idEmpleado;
     private Cargo cargo;
     private String empleadosNombre;
     private String empleadosApellido;
     private  int empleadosCi;
     private String empleadosDir;
     private String empleadosTlfCasa;
     private String empleadosTlfMovil;
     private String empleadosContrasena;
     private Date empleadosFechaIng;
     private Date empleadosFechaFin;
     private Integer empleadosSueldoBase;
     private String empleadosLogin;
     private String empleadosCorreo;

    public Empleados() {
    }

	
    public Empleados(int id, Cargo cargo, String empleadosNombre, String empleadosApellido, int empleadosCi, String empleadosContrasena, Date empleadosFechaIng, String empleadosLogin, String empleadosCorreo) {
        this.idEmpleado = id;
        this.cargo = cargo;
        this.empleadosNombre = empleadosNombre;
        this.empleadosApellido = empleadosApellido;
        this.empleadosCi = empleadosCi;
        this.empleadosContrasena = empleadosContrasena;
        this.empleadosFechaIng = empleadosFechaIng;
        this.empleadosLogin = empleadosLogin;
        this.empleadosCorreo = empleadosCorreo;
    }
    
    public Empleados(int id, Cargo cargo, String empleadosNombre, String empleadosApellido, int empleadosCi, String empleadosDir, String empleadosTlfCasa, String empleadosTlfMovil, String empleadosContrasena, Date empleadosFechaIng, Date empleadosFechaFin, Integer empleadosSueldoBase, String empleadosLogin, String empleadosCorreo) {
       this.idEmpleado = id;
       this.cargo = cargo;
       this.empleadosNombre = empleadosNombre;
       this.empleadosApellido = empleadosApellido;
       this.empleadosCi = empleadosCi;
       this.empleadosDir = empleadosDir;
       this.empleadosTlfCasa = empleadosTlfCasa;
       this.empleadosTlfMovil = empleadosTlfMovil;
       this.empleadosContrasena = empleadosContrasena;
       this.empleadosFechaIng = empleadosFechaIng;
       this.empleadosFechaFin = empleadosFechaFin;
       this.empleadosSueldoBase = empleadosSueldoBase;
       this.empleadosLogin = empleadosLogin;
       this.empleadosCorreo = empleadosCorreo;
    }
   
    public int getId() {
        return this.idEmpleado;
    }
    
    private void setId(int id) {
        this.idEmpleado = id;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getEmpleadosNombre() {
        return this.empleadosNombre;
    }
    
    public void setEmpleadosNombre(String empleadosNombre) {
        this.empleadosNombre = empleadosNombre;
    }
    public String getEmpleadosApellido() {
        return this.empleadosApellido;
    }
    
    public void setEmpleadosApellido(String empleadosApellido) {
        this.empleadosApellido = empleadosApellido;
    }
    public int getEmpleadosCi() {
        return this.empleadosCi;
    }
    
    public void setEmpleadosCi(int empleadosCi) {
        this.empleadosCi = empleadosCi;
    }
    public String getEmpleadosDir() {
        return this.empleadosDir;
    }
    
    public void setEmpleadosDir(String empleadosDir) {
        this.empleadosDir = empleadosDir;
    }
    public String getEmpleadosTlfCasa() {
        return this.empleadosTlfCasa;
    }
    
    public void setEmpleadosTlfCasa(String empleadosTlfCasa) {
        this.empleadosTlfCasa = empleadosTlfCasa;
    }
    public String getEmpleadosTlfMovil() {
        return this.empleadosTlfMovil;
    }
    
    public void setEmpleadosTlfMovil(String empleadosTlfMovil) {
        this.empleadosTlfMovil = empleadosTlfMovil;
    }
    public String getEmpleadosContrasena() {
        return this.empleadosContrasena;
    }
    
    public void setEmpleadosContrasena(String empleadosContrasena) {
        this.empleadosContrasena = empleadosContrasena;
    }
    public Date getEmpleadosFechaIng() {
        return this.empleadosFechaIng;
    }
    
    public void setEmpleadosFechaIng(Date empleadosFechaIng) {
        this.empleadosFechaIng = empleadosFechaIng;
    }
    public Date getEmpleadosFechaFin() {
        return this.empleadosFechaFin;
    }
    
    public void setEmpleadosFechaFin(Date empleadosFechaFin) {
        this.empleadosFechaFin = empleadosFechaFin;
    }
    public Integer getEmpleadosSueldoBase() {
        return this.empleadosSueldoBase;
    }
    
    public void setEmpleadosSueldoBase(Integer empleadosSueldoBase) {
        this.empleadosSueldoBase = empleadosSueldoBase;
    }
    public String getEmpleadosLogin() {
        return this.empleadosLogin;
    }
    
    public void setEmpleadosLogin(String empleadosLogin) {
        this.empleadosLogin = empleadosLogin;
    }
    public String getEmpleadosCorreo() {
        return this.empleadosCorreo;
    }
    
    public void setEmpleadosCorreo(String empleadosCorreo) {
        this.empleadosCorreo = empleadosCorreo;
    }




}


