package datos;
// Generated May 23, 2010 7:11:23 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private int idCargo;
     private String cargoDescripcion;
     private Set empleadoses = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(int idCargo, String cargoDescripcion) {
        this.idCargo = idCargo;
        this.cargoDescripcion = cargoDescripcion;
    }
    public Cargo(int idCargo, String cargoDescripcion, Set empleadoses) {
       this.idCargo = idCargo;
       this.cargoDescripcion = cargoDescripcion;
       this.empleadoses = empleadoses;
    }
   
    public int getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }
    public String getCargoDescripcion() {
        return this.cargoDescripcion;
    }
    
    public void setCargoDescripcion(String cargoDescripcion) {
        this.cargoDescripcion = cargoDescripcion;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


